### ISSUE TITLE
Load Query from a file

### ISSUE THREAD

**Issue by johnjarrard** [hasankhan/sql-cli#42]
Is there a way to pipe in a set of queries stored in a .sql file?  In SQLCMD, the argument is -i.

I've attempted to pipe in a file into the -q argument, but it doesn't seem to work.  Any ideas how I could do that?

**Comment by hasankhan** [comment]
mssql -q ".run filename.sql"

**Comment by stguitar** [comment]
@hasankhan This is great - would it be possible to expose a command line option to do this with an -i parameter, much like the sqlcmd utility directly on the shell?  main reason would be so that you you could use your history and tab completion, etc to quickly execute stuff like this.  our project has a sql folder where we keep all of our stored procedures. as i change those, i need to execute those against the database and it would nice if i had a command line way (without shelling into the server to run sqlcmd)

**Comment by stguitar** [comment]
@hasankhan ill also say that i may be able to help add this functionality

**Comment by hasankhan** [comment]
Cool, please go ahead, make the change and send a pull request. Thanks.

**Comment by stguitar** [comment]
@hasankhan just a heads up, i do plan to submit a PR for this, just got a bit backed up for a bit with other things first

**Comment by hasankhan** [comment]
Cool, looking forward to it. Please add unit test with your changes and target the pull request at dev branch.
